//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ресторан
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Ресторан1Entities : DbContext
    {
        private static Ресторан1Entities _context;
        public Ресторан1Entities()
            : base("name=Ресторан1Entities")
        {
        }

        public static Ресторан1Entities GetContext()
        {
            if (_context == null)
                _context = new Ресторан1Entities();

            return _context;
        }


        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Блюдо> Блюдо { get; set; }
        public virtual DbSet<Заказ> Заказ { get; set; }
        public virtual DbSet<Пользователь> Пользователь { get; set; }
        public virtual DbSet<СтрокаЗаказа> СтрокаЗаказа { get; set; }
        public virtual DbSet<ФотоБлюда> ФотоБлюда { get; set; }
    }
}
