//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ресторан
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    
    public partial class Блюдо
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Блюдо()
        {
            this.СтрокаЗаказа = new HashSet<СтрокаЗаказа>();
            this.ФотоБлюда = new HashSet<ФотоБлюда>();
        }
    
        public int ИД_блюда { get; set; }
        public string Название { get; set; }
        public decimal Стоимость { get; set; }

        public string ImgPath
        {
            get
            {
                if (File.Exists(Directory.GetCurrentDirectory() + @"\Resources\" + this.Название + ".jpg"))
                {
                    return "/Resources/" + this.Название + ".jpg";
                }
                else
                {
                    return "/Resources/picture.png";
                }
            }
        }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<СтрокаЗаказа> СтрокаЗаказа { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ФотоБлюда> ФотоБлюда { get; set; }
    }
}
